import * as fs from "fs";
import * as path from "path";
import sharp from "sharp";

const IMG_DIR = path.join(process.cwd(), "public/img");
const OUTPUT_FILE = path.join(process.cwd(), "src/lib/lqip.ts");

async function generateLqip() {
  const files = fs.readdirSync(IMG_DIR);
  const imageFiles = files.filter((f) =>
    /\.(jpg|jpeg|png|webp|gif)$/i.test(f),
  );

  const lqipMap: Record<string, string> = {};

  for (const file of imageFiles) {
    const inputPath = path.join(IMG_DIR, file);
    const imagePath = `/img/${file}`;

    try {
      const buffer = await sharp(inputPath)
        .resize(8, 8, { fit: "inside" })
        .jpeg({ quality: 50 })
        .toBuffer();

      const base64 = buffer.toString("base64");
      lqipMap[imagePath] = `data:image/jpeg;base64,${base64}`;

      console.log(`✓ ${file}`);
    } catch (error) {
      console.error(`✗ ${file}: ${(error as Error).message}`);
    }
  }

  const output = `// Auto-generated by scripts/generate-lqip.ts
// Do not edit manually - run \`npm run lqip\` to regenerate

export const lqip: Record<string, string> = ${JSON.stringify(lqipMap, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(
    `\nGenerated ${Object.keys(lqipMap).length} LQIPs to ${OUTPUT_FILE}`,
  );
}

generateLqip().catch(console.error);
