name: Production Rollback

on:
  workflow_dispatch:

jobs:
  rollback:
    name: Rollback Production
    permissions:
      contents: read
    uses: yongchenglow/ci-workflows/.github/workflows/production-rollback.yml@v1
    secrets: inherit
