name: Production Rollback

on:
  workflow_dispatch:

jobs:
  rollback:
    name: Rollback Production
    permissions:
      contents: read
      deployments: read
    uses: yongchenglow/ci-workflows/.github/workflows/production-rollback.yml@v2
    with:
      application_name: yongchenglow
      namespace: personal-site
      release_name: web
      production_hostname: ${{ vars.CLOUDFLARE_DOMAIN }}
    secrets: inherit
